version: "3"
services:
    db:
        image: postgres:15
        env_file:
            - ../.env
        volumes:
            - postgres_data:/var/lib/postgresql/data/

    web:
        build: ../backend/
        env_file:
            - ../.env
        ports:
            - 8000:8000
        volumes:
            - static_value:/app/collectstatic/
            - media_value:/app/media/
        depends_on:
            - db

    nginx:
        build: ../gateway
        ports:
            - 80:80
        volumes:
            - static_value:/var/html/static/
            - media_value:/var/html/media/

volumes:
    postgres_data:
    static_value:
    media_value:
